#!/bin/sh -e

PROJECT=${1?"Usage: $0 PROJECT"}

LOWER="$(awk '{print tolower($0)}' <<< $PROJECT)"
TITLE="$(awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}' <<< $PROJECT)"

mv "ambiata-project.cabal" "ambiata-${LOWER}.cabal"
mv "src/Project.hs" "src/${TITLE}.hs"

for FILE in $(find . -type f ! -path ./lib/\* ! -path ./.git/\* ! -path ./init); do
  sed -i '' "s/project/$LOWER/g" "$FILE"
  sed -i '' "s/Project/$TITLE/g" "$FILE"
done

git add .
git rm --cached "${BASH_SOURCE[0]}"
git commit -v

rm "${BASH_SOURCE[0]}"
